# Generated by Django 4.1.7 on 2023-04-01 18:13

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hackathon", "0002_hackathon_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="teams",
            field=models.ManyToManyField(
                blank=True, default=True, null=True, to="hackathon.team"
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="team",
            name="member",
            field=models.ManyToManyField(
                blank=True, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
