# Generated by Django 4.1.7 on 2023-04-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathon", "0004_hackathon_address_hackathon_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="media"),
        ),
    ]
