# Generated by Django 4.1.7 on 2023-04-01 23:35

from django.db import migrations, models
import hackathon.models


class Migration(migrations.Migration):

    dependencies = [
        ("hackathon", "0005_alter_hackathon_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="code",
            field=models.CharField(
                default=hackathon.models.generate_short_uuid, max_length=6
            ),
        ),
    ]
