# Generated by Django 4.1.7 on 2023-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="user",
            name="college_name",
            field=models.CharField(default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="graduation_completion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
