# Generated by Django 4.1.7 on 2023-04-01 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="admin_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="keyword_rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
